<a href="https://colab.research.google.com/github/muajnstu/Customer_Churn_Prediction/blob/main/Employee_Attrition_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Libraries

In [ ]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression, SGDClassifier
from sklearn.svm import SVC, NuSVC, LinearSVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier, ExtraTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, AdaBoostClassifier, ExtraTreesClassifier
from sklearn.naive_bayes import GaussianNB, BernoulliNB
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis, QuadraticDiscriminantAnalysis
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score, precision_score, f1_score, recall_score, roc_auc_score

In [ ]:
def train_and_evaluate_models(models, X_train, X_test, y_train, y_test):
    results = {}
    for name, model in models.items():
        print(f"Training {name}...")
        model.fit(X_train, y_train)
        y_pred = model.predict(X_test)

        accuracy = accuracy_score(y_test, y_pred)
        precision = precision_score(y_test, y_pred)
        f1 = f1_score(y_test, y_pred)
        recall = recall_score(y_test, y_pred)
        auc = roc_auc_score(y_test, y_pred)

        results[name] = {
            'accuracy': accuracy,
            'precision': precision,
            'f1_score': f1,
            'recall': recall,
            'auc': auc
        }

        print(f"{name} metrics:")
        print(f"  Accuracy: {accuracy:.4f}")
        print(f"  Precision: {precision:.4f}")
        print(f"  F1 Score: {f1:.4f}")
        print(f"  Recall: {recall:.4f}")
        print(f"  AUC: {auc:.4f}")

    return results

# Data Loading

In [ ]:
liza=pd.read_csv('https://raw.githubusercontent.com/muajnstu/ML-Datasets/refs/heads/main/employee_attrition_data.csv')

In [ ]:
liza

,Employee_ID,Age,Gender,Department,Job_Title,Years_at_Company,Satisfaction_Level,Average_Monthly_Hours,Promotion_Last_5Years,Salary,Attrition
0,0,27,Male,Marketing,Manager,9,0.586251,151,0,60132,0
1,1,53,Female,Sales,Engineer,10,0.261161,221,1,79947,0
2,2,59,Female,Marketing,Analyst,8,0.304382,184,0,46958,1
3,3,42,Female,Engineering,Manager,1,0.480779,242,0,40662,0
4,4,44,Female,Sales,Engineer,10,0.636244,229,1,74307,0
...,...,...,...,...,...,...,...,...,...,...,...
995,995,39,Female,HR,HR Specialist,3,0.377435,239,0,71403,0
996,996,50,Male,Engineering,Manager,1,0.431152,154,0,30181,1
997,997,52,Male,Engineering,Analyst,3,0.647102,206,0,64143,0
998,998,37,Female,HR,HR Specialist,2,0.304813,241,0,74383,1
999,999,59,Male,Sales,HR Specialist,1,0.940510,159,0,73220,1

In [ ]:
liza.duplicated().sum()
print(liza.duplicated().sum())

0

In [ ]:
liza.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Employee_ID            1000 non-null   int64
 1   Age                    1000 non-null   int64
 2   Gender                 1000 non-null   object
 3   Department             1000 non-null   object
 4   Job_Title              1000 non-null   object
 5   Years_at_Company       1000 non-null   int64
 6   Satisfaction_Level     1000 non-null   float64
 7   Average_Monthly_Hours  1000 non-null   int64
 8   Promotion_Last_5Years  1000 non-null   int64
 9   Salary                 1000 non-null   int64
 10  Attrition              1000 non-null   int64
dtypes: float64(1), int64(7), object(3)
memory usage: 86.1+ KB

In [ ]:
liza['Attrition'].value_counts()

Attrition
0    505
1    495
Name: count, dtype: int64

In [ ]:
for col in liza.columns:
    print(f"Unique values for column '{col}':")
    print(liza[col].unique())
    print("\n")

Unique values for column 'Employee_ID':
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251
 252 253 254 255 256 257 258 259 260 261 262 263 264 265 266 267 268 269
 270 271 272 273 274 275 276 277 278 279 280 281 282 283 284 285 286 287
 288 289 290 291 292 293 294 295 296 297 298 299 300 301 302 303 304 305
 306 307 308 309 310 311 312 313 314 315 316 317 318 319 320 321 322 323
 324 325 326 327 328 329 330 331 332 333 334 335 336 337 338 339 340 341
 342 343 344 345 346 347 348 349 350 351 352 353 354 355 356 357 358 359
 360 361 362 363 364 365 366 367 368 369 370 371 372 373 374 375 376 377
 378 379 380 381 382 383 384 385 386 387 388 389 390 391 392 393 394 395
 396 397 398 399 400 401 402 403 404 405 406 407 408 409 410 411 412 413
 414 415 416 417 418 419 420 421 422 423 424 425 426 427 428 429 430 431
 432 433 434 435 436 437 438 439 440 441 442 443 444 445 446 447 448 449
 450 451 452 453 454 455 456 457 458 459 460 461 462 463 464 465 466 467
 468 469 470 471 472 473 474 475 476 477 478 479 480 481 482 483 484 485
 486 487 488 489 490 491 492 493 494 495 496 497 498 499 500 501 502 503
 504 505 506 507 508 509 510 511 512 513 514 515 516 517 518 519 520 521
 522 523 524 525 526 527 528 529 530 531 532 533 534 535 536 537 538 539
 540 541 542 543 544 545 546 547 548 549 550 551 552 553 554 555 556 557
 558 559 560 561 562 563 564 565 566 567 568 569 570 571 572 573 574 575
 576 577 578 579 580 581 582 583 584 585 586 587 588 589 590 591 592 593
 594 595 596 597 598 599 600 601 602 603 604 605 606 607 608 609 610 611
 612 613 614 615 616 617 618 619 620 621 622 623 624 625 626 627 628 629
 630 631 632 633 634 635 636 637 638 639 640 641 642 643 644 645 646 647
 648 649 650 651 652 653 654 655 656 657 658 659 660 661 662 663 664 665
 666 667 668 669 670 671 672 673 674 675 676 677 678 679 680 681 682 683
 684 685 686 687 688 689 690 691 692 693 694 695 696 697 698 699 700 701
 702 703 704 705 706 707 708 709 710 711 712 713 714 715 716 717 718 719
 720 721 722 723 724 725 726 727 728 729 730 731 732 733 734 735 736 737
 738 739 740 741 742 743 744 745 746 747 748 749 750 751 752 753 754 755
 756 757 758 759 760 761 762 763 764 765 766 767 768 769 770 771 772 773
 774 775 776 777 778 779 780 781 782 783 784 785 786 787 788 789 790 791
 792 793 794 795 796 797 798 799 800 801 802 803 804 805 806 807 808 809
 810 811 812 813 814 815 816 817 818 819 820 821 822 823 824 825 826 827
 828 829 830 831 832 833 834 835 836 837 838 839 840 841 842 843 844 845
 846 847 848 849 850 851 852 853 854 855 856 857 858 859 860 861 862 863
 864 865 866 867 868 869 870 871 872 873 874 875 876 877 878 879 880 881
 882 883 884 885 886 887 888 889 890 891 892 893 894 895 896 897 898 899
 900 901 902 903 904 905 906 907 908 909 910 911 912 913 914 915 916 917
 918 919 920 921 922 923 924 925 926 927 928 929 930 931 932 933 934 935
 936 937 938 939 940 941 942 943 944 945 946 947 948 949 950 951 952 953
 954 955 956 957 958 959 960 961 962 963 964 965 966 967 968 969 970 971
 972 973 974 975 976 977 978 979 980 981 982 983 984 985 986 987 988 989
 990 991 992 993 994 995 996 997 998 999]


Unique values for column 'Age':
[27 53 59 42 44 47 58 57 34 50 39 41 29 28 45 32 46 55 52 37 30 25 36 35
 38 43 40 31 51 26 48 54 49 33 56]


Unique values for column 'Gender':
['Male' 'Female']


Unique values for column 'Department':
['Marketing' 'Sales' 'Engineering' 'Finance' 'HR']


Unique values for column 'Job_Title':
['Manager' 'Engineer' 'Analyst' 'HR Specialist' 'Accountant']


Unique values for column 'Years_at_Company':
[ 9 10  8  1  5  6  7  3  4  2]


Unique values for column 'Satisfaction_Level':
[0.58625126 0.26116089 0.30438172 0.48077887 0.63624389 0.88901767
 0.68897658 0.98167869 0.0103809  0.46678236 0.36262507 0.17710699
 0.23423706 0.22719848 0.82221207 0.58345431 0.40119268 0.51871548
 0.84821687 0.52328018 0.09859819 0.64553991 0.6532311  0.62327361
 0.92187319 0.21223972 0.99749831 0.06841183 0.77941911 0.61478262
 0.79157677 0.35498995 0.99723219 0.12600313 0.63798011 0.96348125
 0.62935992 0.5478732  0.4250007  0.6735533  0.8142447  0.42150387
 0.9900197  0.45647329 0.28378233 0.59769708 0.0688672  0.19864105
 0.32201773 0.79230019 0.18553526 0.61467057 0.98285514 0.75059755
 0.47546047 0.81216125 0.12078444 0.58889365 0.38029249 0.9083694
 0.31056809 0.68848398 0.23298725 0.75333242 0.97887789 0.46356554
 0.88749414 0.34934946 0.38406342 0.11492343 0.93990641 0.51768382
 0.43311433 0.06794745 0.07443842 0.28803291 0.85474565 0.94195298
 0.71293727 0.86677427 0.80134616 0.97597989 0.39845176 0.83018141
 0.91644361 0.80705319 0.86163177 0.0013765  0.71137618 0.42704324
 0.22382838 0.87322287 0.48856621 0.00839091 0.17876103 0.12918158
 0.90315971 0.72295974 0.44896299 0.34121853 0.00657366 0.28540027
 0.66254372 0.70420365 0.81199696 0.42645247 0.792033   0.87723955
 0.07677753 0.066899   0.93609515 0.26106443 0.49288046 0.01918425
 0.33856585 0.46765648 0.37689089 0.05075933 0.68908219 0.75174098
 0.94852166 0.52449771 0.03928127 0.12707358 0.88956857 0.87833409
 0.86546828 0.2309575  0.07253299 0.16093663 0.38112151 0.68764588
 0.67670174 0.69263096 0.4173951  0.30236362 0.67174403 0.9565822
 0.67724849 0.61064534 0.51349801 0.78989787 0.77240706 0.56496158
 0.09108799 0.48160477 0.69348321 0.03335343 0.39613433 0.09217355
 0.12271644 0.81200178 0.69110791 0.670189   0.95545306 0.61609067
 0.84830248 0.37711948 0.17058648 0.6362806  0.80425112 0.14996185
 0.29839696 0.33693689 0.83643064 0.02315387 0.777464   0.28580663
 0.23671189 0.53993739 0.30386938 0.77640932 0.77028042 0.35967949
 0.74819484 0.27554456 0.4642992  0.82957692 0.30541744 0.13038396
 0.14071759 0.16379955 0.40821774 0.52733143 0.74560968 0.13543013
 0.89442122 0.92479973 0.76027645 0.30616167 0.23960892 0.32305239
 0.75316552 0.48538942 0.84782031 0.0813347  0.90502404 0.35356843
 0.61420161 0.18521265 0.03759362 0.21489408 0.41534398 0.01371413
 0.98278249 0.18975302 0.87015707 0.72244045 0.75591185 0.60661359
 0.88272069 0.62962212 0.23858496 0.05359173 0.94855235 0.62941214
 0.17587409 0.00996642 0.31393745 0.56069128 0.30666787 0.47911376
 0.02860913 0.54060845 0.5472466  0.76069311 0.8744154  0.27038928
 0.96953314 0.17704375 0.47789661 0.78034968 0.8737839  0.10828306
 0.04165748 0.92528813 0.65194475 0.8356135  0.74674419 0.72574244
 0.42214048 0.7049426  0.12408832 0.38848664 0.73512407 0.42483874
 0.98572452 0.9246925  0.27703426 0.88222486 0.82425147 0.4703071
 0.42006102 0.23539179 0.60114567 0.58479374 0.33271124 0.6326438
 0.66265142 0.50317012 0.88251207 0.78883245 0.06580262 0.46172506
 0.21175598 0.54458208 0.2130503  0.89105456 0.05229242 0.83253431
 0.4103787  0.60636543 0.26026792 0.60279341 0.18551519 0.80680452
 0.59643825 0.64864072 0.26467275 0.16781895 0.03690029 0.16673618
 0.36598324 0.90835338 0.78283706 0.22400198 0.02053187 0.23444365
 0.90178692 0.32464811 0.56298941 0.47689399 0.53830966 0.8942346
 0.32022659 0.55559286 0.48252713 0.63666195 0.78086503 0.27619663
 0.42055738 0.17622931 0.03082915 0.34333007 0.30433489 0.96409956
 0.89433578 0.24518646 0.10840193 0.95346294 0.43313522 0.19107567
 0.84236854 0.8457289  0.55737945 0.10817035 0.98186939 0.00607168
 0.81614119 0.38393758 0.95456333 0.96289385 0.77160915 0.2867072
 0.02312074 0.99059585 0.90704791 0.4717567  0.80660397 0.4296448
 0.51558947 0.50228121 0.17559617 0.4674457  0.46869061 0.90452471
 0.6762723  0.62110016 0.67408074 0.60123401 0.21548145 0.11684824
 0.92068925 0.76809449 0.24505486 0.75167583 0.17853183 0.73881706
 0.3928066  0.00791925 0.07064511 0.47219371 0.03100928 0.39446132
 0.30803109 0.10599521 0.45793599 0.11597912 0.18586285 0.92670729
 0.44222022 0.6857796  0.96568751 0.13766877 0.36418031 0.84587039
 0.1044322  0.64048831 0.83233889 0.10869912 0.85953267 0.73973033
 0.50868341 0.96001635 0.50474486 0.75195498 0.94435667 0.08520947
 0.19763839 0.91588518 0.93938439 0.32042556 0.96186604 0.43448102
 0.11436755 0.32099136 0.345618   0.49646795 0.21498438 0.15765283
 0.26114702 0.88385417 0.0660869  0.54495817 0.35537153 0.43732693
 0.72164596 0.96747283 0.94925177 0.74932508 0.21231072 0.20114881
 0.27552579 0.74874561 0.35515769 0.26130881 0.42928456 0.01490187
 0.60695493 0.46780782 0.92172073 0.36332824 0.02861073 0.72311329
 0.60759922 0.45974073 0.92664352 0.52136439 0.26230967 0.90396527
 0.46455426 0.73079395 0.46756822 0.37369884 0.02661864 0.80010954
 0.70159329 0.11285657 0.49929617 0.65692605 0.48174424 0.91646126
 0.72044774 0.09336473 0.86441995 0.51279395 0.89282117 0.83953376
 0.92053076 0.94907116 0.78505472 0.73203574 0.49065126 0.98851215
 0.48338619 0.70006597 0.82445991 0.23770738 0.67817074 0.51633463
 0.81934838 0.47625331 0.79705062 0.20928214 0.42128209 0.10949781
 0.23153101 0.14725599 0.8083483  0.54175135 0.73690844 0.74399834
 0.2805922  0.60702741 0.56979934 0.49007604 0.06652847 0.35923806
 0.67483438 0.17439786 0.05467597 0.37563954 0.07453669 0.77320922
 0.83506439 0.72583559 0.32420582 0.87480596 0.03885377 0.33009705
 0.1485178  0.77227378 0.87806586 0.63953183 0.77108011 0.31631876
 0.48521785 0.43166451 0.21418929 0.85104898 0.53870036 0.03514593
 0.27004591 0.12553209 0.15111769 0.60156912 0.05986489 0.00284401
 0.85911387 0.29001923 0.72047743 0.69606287 0.42445214 0.53585906
 0.39868527 0.12568902 0.84659847 0.6557075  0.23495537 0.96218951
 0.1591832  0.67258837 0.09521665 0.76757849 0.2007893  0.08730692
 0.29652133 0.07549003 0.80437413 0.78750477 0.89692512 0.88904467
 0.82601985 0.32009653 0.83946935 0.33236726 0.10768654 0.84448044
 0.36134222 0.35674194 0.67014676 0.33211479 0.30145012 0.42677927
 0.57960323 0.22210474 0.85260886 0.96868517 0.33008718 0.57680955
 0.97316954 0.83106524 0.67712711 0.25938697 0.56269851 0.06923311
 0.19208015 0.01044482 0.8645314  0.2750603  0.22895796 0.9048225
 0.47827649 0.29893162 0.05178753 0.02395112 0.02072105 0.62025233
 0.87076828 0.65499339 0.42993985 0.69046023 0.47564858 0.11351919
 0.39404943 0.25208507 0.40071023 0.80364643 0.50979134 0.21589585
 0.5278602  0.52661781 0.48551638 0.3658944  0.58051584 0.17680844
 0.56380663 0.08471897 0.68484402 0.13414635 0.95009501 0.81230879
 0.4360903  0.14760291 0.93166228 0.4869832  0.02137188 0.123713
 0.50594027 0.45198424 0.86271264 0.87006302 0.95258519 0.47503462
 0.95692065 0.30657561 0.06140798 0.53907975 0.22168156 0.95665244
 0.47270858 0.19353322 0.18651915 0.19644401 0.08549576 0.38379319
 0.34660001 0.43229849 0.62567632 0.51021464 0.48053321 0.85703668
 0.22819299 0.32376796 0.63659423 0.10723242 0.80468572 0.81304869
 0.28048272 0.26623242 0.20912515 0.31549    0.6147834  0.45335555
 0.26179434 0.98332399 0.40086191 0.31082255 0.93406122 0.73257237
 0.06453554 0.16417062 0.78623374 0.41456418 0.10133275 0.32877709
 0.63616241 0.63000317 0.17842141 0.74735757 0.38739736 0.74386809
 0.63454582 0.0752315  0.15550339 0.74380972 0.1059544  0.20163558
 0.8623329  0.9639111  0.20978796 0.21283922 0.4789064  0.17437029
 0.62161134 0.74121508 0.75642743 0.89790821 0.24367723 0.96149373
 0.01864332 0.99997727 0.58433319 0.68091578 0.15117563 0.1220463
 0.28498044 0.56796227 0.12694501 0.93439406 0.76965245 0.32193888
 0.98440719 0.98069879 0.32241648 0.76246034 0.22834374 0.12575532
 0.78666502 0.57273681 0.48850561 0.48984626 0.99997865 0.63804536
 0.76632302 0.03892912 0.78892382 0.06839374 0.01936748 0.55298868
 0.77028011 0.46552465 0.00900879 0.47284973 0.64554773 0.20410738
 0.45878617 0.95423285 0.43394239 0.51058358 0.50586135 0.76252154
 0.99004256 0.0917277  0.10570166 0.57310653 0.97020971 0.15374113
 0.89245956 0.39421057 0.45846382 0.64432008 0.69937911 0.25730248
 0.32308811 0.27639336 0.89163912 0.68678088 0.29758929 0.10505132
 0.02083963 0.86874448 0.21668314 0.15767492 0.9887872  0.1614307
 0.65624188 0.21743519 0.61664381 0.67288057 0.86654913 0.51793508
 0.83655343 0.10362885 0.35515976 0.01270832 0.37035258 0.03975538
 0.96964323 0.59805378 0.4048085  0.5852541  0.37924449 0.04864141
 0.80380238 0.14930507 0.59310635 0.0708219  0.6495113  0.24421308
 0.79622253 0.88045125 0.33060536 0.54988736 0.81048426 0.41779234
 0.21516024 0.02203779 0.6776539  0.65061477 0.15998903 0.63452471
 0.5365095  0.14968203 0.20988269 0.47163017 0.59851075 0.70110427
 0.10758229 0.30047019 0.97003503 0.87215575 0.9476901  0.35095129
 0.61705273 0.87882555 0.13219448 0.05628714 0.61211339 0.55754052
 0.75800091 0.16928262 0.79652558 0.82445542 0.19689658 0.37626586
 0.41052788 0.17564103 0.28790652 0.18368085 0.77613839 0.48105511
 0.71791911 0.85951637 0.89752829 0.03157071 0.55647254 0.95849039
 0.8386824  0.87137089 0.36488791 0.70793313 0.48133703 0.59945274
 0.69540388 0.62113263 0.69328418 0.56547489 0.45437572 0.28808465
 0.64819396 0.36338063 0.81105003 0.72551822 0.34672665 0.51677883
 0.23430445 0.9246216  0.2981684  0.92074042 0.05895631 0.18079983
 0.63306174 0.54048889 0.85543053 0.80158243 0.08109502 0.28605449
 0.56279997 0.22052089 0.81883505 0.79522173 0.33118442 0.92387098
 0.67622876 0.27923373 0.65162912 0.42376696 0.00896353 0.60052427
 0.11420032 0.22227051 0.74214854 0.71360847 0.01315362 0.38917992
 0.41890737 0.35528804 0.59708329 0.38259761 0.02850785 0.79852072
 0.54056071 0.05399577 0.39622113 0.86272413 0.52581912 0.71902117
 0.59412501 0.55124205 0.76507464 0.65980067 0.14138316 0.93591346
 0.80046417 0.81868213 0.66770848 0.66954987 0.10151831 0.46539682
 0.86689545 0.38150258 0.4123721  0.16676333 0.11168616 0.36804016
 0.88309862 0.16309123 0.61575081 0.08218253 0.19534581 0.67221538
 0.65775272 0.90601698 0.15176921 0.69613374 0.91464028 0.62470647
 0.59463495 0.15300572 0.21819414 0.5711872  0.05710764 0.90420063
 0.41735317 0.66085675 0.4581053  0.78876593 0.61853516 0.60074643
 0.27157482 0.74980132 0.3015213  0.92859346 0.60480475 0.85712738
 0.62802251 0.68234003 0.00463256 0.9172435  0.85398721 0.92742251
 0.0986103  0.1249736  0.376769   0.13268243 0.4815205  0.97222141
 0.62394165 0.9652969  0.40756076 0.30505889 0.17362368 0.49022645
 0.00822813 0.24785737 0.73208328 0.7085857  0.44696677 0.02633343
 0.79814482 0.756786   0.35578757 0.76453047 0.93107523 0.93657283
 0.74537213 0.67831447 0.54845763 0.08619767 0.15555937 0.35452424
 0.58924359 0.54945738 0.74284366 0.32512682 0.3437591  0.66464366
 0.14069382 0.52945156 0.42095119 0.35024167 0.51804958 0.27728485
 0.32004384 0.00484557 0.35150897 0.00182029 0.25307295 0.46428892
 0.351306   0.52747005 0.79335704 0.92905267 0.33429805 0.73888197
 0.67467316 0.3032872  0.62178423 0.13530334 0.88308277 0.92132569
 0.65829914 0.21366289 0.61047254 0.79031401 0.35287028 0.50548872
 0.6973752  0.79612731 0.4394224  0.91419234 0.94966446 0.7169266
 0.09737525 0.57371782 0.09370428 0.38200371 0.7900777  0.7184663
 0.55851178 0.88962076 0.95509472 0.9324496  0.99201794 0.37743487
 0.43115213 0.64710249 0.30481271 0.94051012]


Unique values for column 'Average_Monthly_Hours':
[151 221 184 242 229 237 155 171 177 170 178 158 180 249 199 222 169 193
 154 211 172 191 216 160 162 224 156 183 194 203 212 220 247 201 161 214
 226 153 186 200 217 228 223 209 233 238 236 173 196 195 165 245 202 168
 185 225 190 218 227 192 167 204 157 163 176 150 244 187 207 182 189 239
 246 232 235 210 240 175 241 243 181 159 215 206 188 219 213 166 231 248
 164 174 234 152 197 208 205 179 230 198]


Unique values for column 'Promotion_Last_5Years':
[0 1]


Unique values for column 'Salary':
[60132 79947 46958 40662 74307 97212 97865 50113 88747 43283 82510 55665
 57951 31886 40548 39979 31340 79639 50307 99568 89409 94005 63445 99093
 95910 80913 59231 68979 65901 85496 91627 91703 51252 63757 84288 86371
 59546 80887 52658 70977 40055 99265 33670 85764 87567 44786 69612 45124
 38871 34599 61224 31506 57428 34834 56938 62841 56230 98061 34647 30269
 41737 71087 50921 89560 59060 46658 82313 91589 48184 58575 80456 72928
 74105 43038 50000 49824 67588 30821 99801 48520 69674 66952 97606 59532
 97663 71807 90011 91398 64897 78600 74424 40798 63948 52415 38085 32082
 58364 40742 84407 76806 81919 70060 99321 93226 81389 38495 70941 99476
 49523 60676 73359 51013 31553 65356 99328 47802 45532 97181 35521 98429
 93166 54477 40012 37543 87607 97217 52961 38532 80112 74736 35031 61668
 58508 62378 73980 78603 45278 50064 92394 40991 76164 37833 90927 86897
 85229 35793 57650 70990 79792 81499 81233 39563 36755 81470 40127 78348
 94455 83240 54977 54598 81682 58653 53838 79759 34808 88563 83237 31256
 83418 43951 63891 94226 89030 57604 63395 65494 82445 75352 78972 62533
 33221 73460 42799 44626 50467 62104 33232 60624 39672 80067 46544 69385
 56338 51112 40223 32762 48449 65708 55484 95558 81643 79587 83416 87098
 46780 71794 30773 43764 88219 72592 85608 65583 91789 99859 60286 53324
 76479 80791 83385 76642 91402 85225 54559 99113 32849 78975 77459 88083
 66740 73275 50184 80830 53625 55262 30935 54878 56322 99851 75106 88135
 71466 43102 61580 96349 84618 68773 39162 66915 34112 97161 91779 87771
 94728 45405 64406 55075 69509 31850 47534 85996 64345 32954 64213 88666
 71088 43095 61200 96615 69501 38068 30859 54641 98610 86372 92828 97244
 88353 54636 73863 35833 70714 42371 70764 48165 84159 64584 46116 47944
 73713 69641 75176 67394 57381 37001 93742 36843 55467 95571 32747 46185
 38604 85832 56461 59075 76410 71557 85613 81026 81995 55051 46767 43261
 93469 93274 52963 71482 58220 92876 46434 39049 93674 87053 34512 59522
 88569 94735 58062 52300 89623 77841 89157 79253 49834 42699 66868 42015
 35610 31053 90843 65174 51874 50329 60973 69286 73505 92988 91629 73737
 34192 37243 78476 72188 71440 72062 77656 46454 82219 49610 41420 50645
 44412 50656 45102 96293 34447 70513 63571 44560 56613 38562 49301 48784
 31815 46467 37004 49158 81385 75317 69252 60839 33966 72481 58506 84131
 57200 69582 86091 72604 38056 89766 83069 59173 62295 32272 40220 65922
 45758 37334 57260 83920 98845 34669 81252 72256 77244 58627 35798 51421
 93822 73509 98405 47841 35265 99071 55071 31472 52874 91705 97650 54467
 63124 76234 33931 51668 80690 66229 64140 50970 60858 48447 34152 32182
 83201 64659 47406 39887 52122 96167 79419 34983 41908 68137 52386 60907
 67919 90686 69158 38395 43501 38228 56690 80428 35568 99206 63229 61098
 63277 47899 32252 83793 45710 93376 62429 46051 98551 98112 70785 83328
 44251 42122 32476 37819 93647 84642 81179 60684 78586 36342 87748 52281
 31475 50116 60563 63836 70312 87579 35273 53055 63425 91437 67147 85742
 68187 90525 81642 42539 97250 33311 74148 38735 43794 73721 68051 87804
 83172 69512 37456 66268 66239 44727 48599 61890 85073 34633 99566 31347
 44704 99991 82078 94130 72752 99584 34172 66406 66024 41439 91504 94294
 89725 31435 56769 93028 43791 48251 77213 94306 93791 51349 83381 31015
 64407 42945 75542 67058 53211 35667 54380 99002 53633 96208 68372 75599
 54308 65562 62728 85262 68662 59461 90263 57042 38343 94611 67607 48220
 46446 58523 42706 38896 92936 46249 55141 89082 92977 35813 85800 94151
 97101 64691 90009 45968 32193 96568 82011 80787 47600 35529 38691 92597
 51575 60435 78199 82555 71559 55788 87535 56368 67056 35721 64692 35293

# Data Cleaning

1. Encoding
2. Drop
3. Correlation

In [ ]:
gender_mapping = {'Male': 0, 'Female': 1}
department_mapping = {'Marketing': 0, 'Sales': 1, 'Engineering': 2, 'Finance': 3, 'HR': 4}
job_title_mapping = {'Manager': 0, 'Engineer': 1, 'Analyst': 2, 'HR Specialist': 3, 'Accountant': 4}
liza['Gender_encoded'] = liza['Gender'].map(gender_mapping)
liza['Department_encoded'] = liza['Department'].map(department_mapping)
liza['Job_Title_encoded'] = liza['Job_Title'].map(job_title_mapping)
print(liza[['Gender', 'Gender_encoded', 'Department', 'Department_encoded', 'Job_Title', 'Job_Title_encoded']].head())
for col in ['Gender_encoded', 'Department_encoded', 'Job_Title_encoded']:
    print(f"Unique values for column '{col}':")
    print(liza[col].unique())
    print("\n")

   Gender  Gender_encoded   Department  Department_encoded Job_Title  \
0    Male               0    Marketing                   0   Manager
1  Female               1        Sales                   1  Engineer
2  Female               1    Marketing                   0   Analyst
3  Female               1  Engineering                   2   Manager
4  Female               1        Sales                   1  Engineer

   Job_Title_encoded
0                  0
1                  1
2                  2
3                  0
4                  1
Unique values for column 'Gender_encoded':
[0 1]


Unique values for column 'Department_encoded':
[0 1 2 3 4]


Unique values for column 'Job_Title_encoded':
[0 1 2 3 4]

In [ ]:
liza.drop(['Employee_ID','Gender', 'Department', 'Job_Title'], axis=1, inplace=True)

In [ ]:
liza.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Age                    1000 non-null   int64
 1   Years_at_Company       1000 non-null   int64
 2   Satisfaction_Level     1000 non-null   float64
 3   Average_Monthly_Hours  1000 non-null   int64
 4   Promotion_Last_5Years  1000 non-null   int64
 5   Salary                 1000 non-null   int64
 6   Attrition              1000 non-null   int64
 7   Gender_encoded         1000 non-null   int64
 8   Department_encoded     1000 non-null   int64
 9   Job_Title_encoded      1000 non-null   int64
dtypes: float64(1), int64(9)
memory usage: 78.3 KB

In [ ]:
liza_corr = liza.corr(method='spearman')
liza_corr

,Age,Years_at_Company,Satisfaction_Level,Average_Monthly_Hours,Promotion_Last_5Years,Salary,Attrition,Gender_encoded,Department_encoded,Job_Title_encoded
Age,1.000000,0.017408,0.022800,-0.028880,0.038948,-0.016899,-0.008769,-0.037304,-0.035719,0.030140
Years_at_Company,0.017408,1.000000,-0.033851,-0.060330,-0.010303,0.036339,0.003381,-0.021234,0.056427,0.023812
Satisfaction_Level,0.022800,-0.033851,1.000000,-0.008978,0.003528,-0.028093,-0.009683,-0.053268,-0.011513,0.024488
Average_Monthly_Hours,-0.028880,-0.060330,-0.008978,1.000000,-0.032078,-0.053435,-0.024612,0.064077,0.002235,-0.004709
Promotion_Last_5Years,0.038948,-0.010303,0.003528,-0.032078,1.000000,0.017535,0.017728,0.007668,-0.042797,0.006831
Salary,-0.016899,0.036339,-0.028093,-0.053435,0.017535,1.000000,-0.037989,0.071726,-0.040775,-0.025963
Attrition,-0.008769,0.003381,-0.009683,-0.024612,0.017728,-0.037989,1.000000,0.033884,0.052450,0.013803
Gender_encoded,-0.037304,-0.021234,-0.053268,0.064077,0.007668,0.071726,0.033884,1.000000,0.003274,-0.033329
Department_encoded,-0.035719,0.056427,-0.011513,0.002235,-0.042797,-0.040775,0.052450,0.003274,1.000000,0.007794
Job_Title_encoded,0.030140,0.023812,0.024488,-0.004709,0.006831,-0.025963,0.013803,-0.033329,0.007794,1.000000

# Model Building

In [ ]:
X = liza.drop('Attrition', axis=1)
y = liza['Attrition']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print("Shape of X_train:", X_train.shape)
print("Shape of X_test:", X_test.shape)
print("Shape of y_train:", y_train.shape)
print("Shape of y_test:", y_test.shape)

Shape of X_train: (800, 9)
Shape of X_test: (200, 9)
Shape of y_train: (800,)
Shape of y_test: (200,)

In [ ]:
models = {
    "LogisticRegression": LogisticRegression(),
    "SVC": SVC(),
    "NuSVC": NuSVC(),
    "LinearSVC": LinearSVC(),
    "KNeighborsClassifier": KNeighborsClassifier(),
    "DecisionTreeClassifier": DecisionTreeClassifier(),
    "ExtraTreeClassifier": ExtraTreeClassifier(),
    "RandomForestClassifier": RandomForestClassifier(),
    "GradientBoostingClassifier": GradientBoostingClassifier(),
    "AdaBoostClassifier": AdaBoostClassifier(),
    "ExtraTreesClassifier": ExtraTreesClassifier(),
    "GaussianNB": GaussianNB(),
    "BernoulliNB": BernoulliNB(),
    "LinearDiscriminantAnalysis": LinearDiscriminantAnalysis(),
    "QuadraticDiscriminantAnalysis": QuadraticDiscriminantAnalysis()
}

# Evaluation

In [ ]:
model_results = train_and_evaluate_models(models, X_train, X_test, y_train, y_test)

Training LogisticRegression...
LogisticRegression metrics:
  Accuracy: 0.4500
  Precision: 0.4318
  F1 Score: 0.4086
  Recall: 0.3878
  AUC: 0.4488
Training SVC...
SVC metrics:
  Accuracy: 0.4800
  Precision: 0.4625
  F1 Score: 0.4157
  Recall: 0.3776
  AUC: 0.4780
Training NuSVC...
NuSVC metrics:
  Accuracy: 0.4150
  Precision: 0.4275
  F1 Score: 0.4891
  Recall: 0.5714
  AUC: 0.4181
Training LinearSVC...
LinearSVC metrics:
  Accuracy: 0.4550
  Precision: 0.4382
  F1 Score: 0.4171
  Recall: 0.3980
  AUC: 0.4539
Training KNeighborsClassifier...

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

KNeighborsClassifier metrics:
  Accuracy: 0.5100
  Precision: 0.5000
  F1 Score: 0.4896
  Recall: 0.4796
  AUC: 0.5094
Training DecisionTreeClassifier...
DecisionTreeClassifier metrics:
  Accuracy: 0.4600
  Precision: 0.4510
  F1 Score: 0.4600
  Recall: 0.4694
  AUC: 0.4602
Training ExtraTreeClassifier...
ExtraTreeClassifier metrics:
  Accuracy: 0.4850
  Precision: 0.4737
  F1 Score: 0.4663
  Recall: 0.4592
  AUC: 0.4845
Training RandomForestClassifier...
RandomForestClassifier metrics:
  Accuracy: 0.4700
  Precision: 0.4500
  F1 Score: 0.4045
  Recall: 0.3673
  AUC: 0.4680
Training GradientBoostingClassifier...
GradientBoostingClassifier metrics:
  Accuracy: 0.4350
  Precision: 0.4227
  F1 Score: 0.4205
  Recall: 0.4184
  AUC: 0.4347
Training AdaBoostClassifier...
AdaBoostClassifier metrics:
  Accuracy: 0.4750
  Precision: 0.4507
  F1 Score: 0.3787
  Recall: 0.3265
  AUC: 0.4721
Training ExtraTreesClassifier...
ExtraTreesClassifier metrics:
  Accuracy: 0.4400
  Precision: 0.4205
  F1 Score: 0.3978
  Recall: 0.3776
  AUC: 0.4388
Training GaussianNB...
GaussianNB metrics:
  Accuracy: 0.4450
  Precision: 0.4316
  F1 Score: 0.4249
  Recall: 0.4184
  AUC: 0.4445
Training BernoulliNB...
BernoulliNB metrics:
  Accuracy: 0.4800
  Precision: 0.4810
  F1 Score: 0.5938
  Recall: 0.7755
  AUC: 0.4858
Training LinearDiscriminantAnalysis...
LinearDiscriminantAnalysis metrics:
  Accuracy: 0.4650
  Precision: 0.4526
  F1 Score: 0.4456
  Recall: 0.4388
  AUC: 0.4645
Training QuadraticDiscriminantAnalysis...
QuadraticDiscriminantAnalysis metrics:
  Accuracy: 0.4200
  Precision: 0.4118
  F1 Score: 0.4200
  Recall: 0.4286
  AUC: 0.4202