<a href="https://colab.research.google.com/github/muajnstu/Customer_Churn_Prediction/blob/main/Employee_Attrition_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Libraries

In [11]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression, SGDClassifier
from sklearn.svm import SVC, NuSVC, LinearSVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier, ExtraTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, AdaBoostClassifier, ExtraTreesClassifier
from sklearn.naive_bayes import GaussianNB, BernoulliNB
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis, QuadraticDiscriminantAnalysis
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score, precision_score, f1_score, recall_score, roc_auc_score
from imblearn.over_sampling import SMOTE

In [2]:
def train_and_evaluate_models(models, X_train, X_test, y_train, y_test):
    results = {}
    for name, model in models.items():
        print(f"Training {name}...")
        model.fit(X_train, y_train)
        y_pred = model.predict(X_test)

        accuracy = accuracy_score(y_test, y_pred)
        precision = precision_score(y_test, y_pred)
        f1 = f1_score(y_test, y_pred)
        recall = recall_score(y_test, y_pred)
        auc = roc_auc_score(y_test, y_pred)

        results[name] = {
            'accuracy': accuracy,
            'precision': precision,
            'f1_score': f1,
            'recall': recall,
            'auc': auc
        }

        print(f"{name} metrics:")
        print(f"  Accuracy: {accuracy:.4f}")
        print(f"  Precision: {precision:.4f}")
        print(f"  F1 Score: {f1:.4f}")
        print(f"  Recall: {recall:.4f}")
        print(f"  AUC: {auc:.4f}")

    return results

# Data Loading

In [3]:
df=pd.read_csv('https://raw.githubusercontent.com/muajnstu/ML-Datasets/refs/heads/main/WA_Fn-UseC_-HR-Employee-Attrition.csv')

In [4]:
df

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,No,Travel_Frequently,884,Research & Development,23,2,Medical,1,2061,...,3,80,1,17,3,3,5,2,0,3
1466,39,No,Travel_Rarely,613,Research & Development,6,1,Medical,1,2062,...,1,80,1,9,5,3,7,7,1,7
1467,27,No,Travel_Rarely,155,Research & Development,4,3,Life Sciences,1,2064,...,2,80,1,6,0,3,6,2,0,3
1468,49,No,Travel_Frequently,1023,Sales,2,3,Medical,1,2065,...,4,80,0,17,3,2,9,6,0,8
1469,34,No,Travel_Rarely,628,Research & Development,8,3,Medical,1,2068,...,1,80,0,6,3,4,4,3,1,2

In [5]:
df.duplicated().sum()
print(df.duplicated().sum())

0

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1470 non-null   int64
 1   Attrition                 1470 non-null   object
 2   BusinessTravel            1470 non-null   object
 3   DailyRate                 1470 non-null   int64
 4   Department                1470 non-null   object
 5   DistanceFromHome          1470 non-null   int64
 6   Education                 1470 non-null   int64
 7   EducationField            1470 non-null   object
 8   EmployeeCount             1470 non-null   int64
 9   EmployeeNumber            1470 non-null   int64
 10  EnvironmentSatisfaction   1470 non-null   int64
 11  Gender                    1470 non-null   object
 12  HourlyRate                1470 non-null   int64
 13  JobInvolvement            1470 non-null   int64
 14  JobLevel                  1470 non-null   int64
 15  JobRole                   1470 non-null   object
 16  JobSatisfaction           1470 non-null   int64
 17  MaritalStatus             1470 non-null   object
 18  MonthlyIncome             1470 non-null   int64
 19  MonthlyRate               1470 non-null   int64
 20  NumCompaniesWorked        1470 non-null   int64
 21  Over18                    1470 non-null   object
 22  OverTime                  1470 non-null   object
 23  PercentSalaryHike         1470 non-null   int64
 24  PerformanceRating         1470 non-null   int64
 25  RelationshipSatisfaction  1470 non-null   int64
 26  StandardHours             1470 non-null   int64
 27  StockOptionLevel          1470 non-null   int64
 28  TotalWorkingYears         1470 non-null   int64
 29  TrainingTimesLastYear     1470 non-null   int64
 30  WorkLifeBalance           1470 non-null   int64
 31  YearsAtCompany            1470 non-null   int64
 32  YearsInCurrentRole        1470 non-null   int64
 33  YearsSinceLastPromotion   1470 non-null   int64
 34  YearsWithCurrManager      1470 non-null   int64
dtypes: int64(26), object(9)
memory usage: 402.1+ KB

In [6]:
df['Attrition'].value_counts()

Attrition
No     1233
Yes     237
Name: count, dtype: int64

Observation: it is an imbalanced dataset

In [7]:
for col in df.columns:
    print(f"Unique values for column '{col}':")
    print(df[col].unique())
    print("\n")

Unique values for column 'Age':
[41 49 37 33 27 32 59 30 38 36 35 29 31 34 28 22 53 24 21 42 44 46 39 43
 50 26 48 55 45 56 23 51 40 54 58 20 25 19 57 52 47 18 60]


Unique values for column 'Attrition':
['Yes' 'No']


Unique values for column 'BusinessTravel':
['Travel_Rarely' 'Travel_Frequently' 'Non-Travel']


Unique values for column 'DailyRate':
[1102  279 1373 1392  591 1005 1324 1358  216 1299  809  153  670 1346
  103 1389  334 1123 1219  371  673 1218  419  391  699 1282 1125  691
  477  705  924 1459  125  895  813 1273  869  890  852 1141  464 1240
 1357  994  721 1360 1065  408 1211 1229  626 1434 1488 1097 1443  515
  853 1142  655 1115  427  653  989 1435 1223  836 1195 1339  664  318
 1225 1328 1082  548  132  746  776  193  397  945 1214  111  573 1153
 1400  541  432  288  669  530  632 1334  638 1093 1217 1353  120  682
  489  807  827  871  665 1040 1420  240 1280  534 1456  658  142 1127
 1031 1189 1354 1467  922  394 1312  750  441  684  249  841  147  528
  594  470  957  542  802 1355 1150 1329  959 1033 1316  364  438  689
  201 1427  857  933 1181 1395  662 1436  194  967 1496 1169 1145  630
  303 1256  440 1450 1452  465  702 1157  602 1480 1268  713  134  526
 1380  140  629 1356  328 1084  931  692 1069  313  894  556 1344  290
  138  926 1261  472 1002  878  905 1180  121 1136  635 1151  644 1045
  829 1242 1469  896  992 1052 1147 1396  663  119  979  319 1413  944
 1323  532  818  854 1034  771 1401 1431  976 1411 1300  252 1327  832
 1017 1199  504  505  916 1247  685  269 1416  833  307 1311  128  488
  529 1210 1463  675 1385 1403  452  666 1158  228  996  728 1315  322
 1479  797 1070  442  496 1372  920  688 1449 1117  636  506  444  950
  889  555  230 1232  566 1302  812 1476  218 1132 1105  906  849  390
  106 1249  192  553  117  185 1091  723 1220  588 1377 1018 1275  798
  672 1162  508 1482  559  210  928 1001  549 1124  738  570 1130 1192
  343  144 1296 1309  483  810  544 1062 1319  641 1332  756  845  593
 1171  350  921 1144  143 1046  575  156 1283  755  304 1178  329 1362
 1371  202  253  164 1107  759 1305  982  821 1381  480 1473  891 1063
  645 1490  317  422 1485 1368 1448  296 1398 1349  986 1099 1116 1499
  983 1009 1303 1274 1277  587  413 1276  988 1474  163  267  619  302
  443  828  561  426  232 1306 1094  509  775  195  258  471  799  956
  535 1495  446 1245  703  823 1246  622 1287  448  254 1365  538  525
  558  782  362 1236 1112  204 1343  604 1216  646  160  238 1397  306
  991  482 1176  913 1076  727  885  243  806  817 1410 1207 1442  693
  929  562  608  580  970 1179  294  314  316  654  168  381  217  501
  650  141  804  975 1090  346  430  268  167  621  527  883  954  310
  719  725  715  657 1146  182  376  571  384  791 1111 1243 1092 1325
  805  213  118  676 1252  286 1258  932 1041  859  720  946 1184  436
  589  760  887 1318  625  180  586 1012  661  930  342 1230 1271 1278
  607  130  300  583 1418 1269  379  395 1265 1222  341  868 1231  102
  881 1383 1075  374 1086  781  177  500 1425 1454  617 1085  995 1122
  618  546  462 1198 1272  154 1137 1188  188 1333  867  263  938  129
  616  498 1404 1053  289 1376  231  152  882  903 1379  335  722  461
  974 1126  840 1134  248  955  939 1391 1206  287 1441  109 1066  277
  466 1055  265  135  247 1035  266  145 1038 1234 1109 1089  788  124
  660 1186 1464  796  415  769 1003 1366  330 1492 1204  309 1330  469
  697 1262 1050  770  406  203 1308  984  439  793 1451 1182  174  490
  718  433  773  603  874  367  199  481  647 1384  902  819  862 1457
  977  942 1402 1421 1361  917  200  150  179  696  116  363  107 1465
  458 1212 1103  966 1010  326 1098  969 1167  694 1320  536  373  599
  251  131  237 1429  648  735  531  429  968  879  640  412  848  360
 1138  325 1322  299 1030  634  524  256 1060  935  495  282  206  943
  523  507  601  855 1291 1405 1369  999 1202  285  404  736 1498 1200
 1439  499  205  683 1462  949  652  332 1475  337  971 1174  667  560
  172  383 1255  359  401  377  592 1445 1221  866  981  447 1326  748
  990  405  115  790  830 1193 1423  467  271  410 1083  516  224  136
 1029  333 1440  674 1342  898  824  492  598  740  888 1288  104 1108
  479 1351  474  437  884 1370  264 1059  563  457 1313  241 1015  336
 1387  170  208  671  711  737 1470  365  763  567  486  772  301  311
  584  880  392  148  708 1259  786  370  678  146  581  918 1238  585
  741  552  369  717  543  964  792  611  176  897  600 1054  428  181
  211 1079  590  305  953  478 1375  244  511 1294  196  734 1239 1253
 1128 1336  234  766  261 1194  431  572 1422 1297  574  355  207  706
  280  726  414  352 1224  459 1254 1131  835 1172 1266  783  219 1213
 1096 1251 1394  605 1064 1337  937  157  754 1168  155 1444  189  911
 1321 1154  557  642  801  161 1382 1037  105  582  704  345 1120 1378
  468  613 1023  628]


Unique values for column 'Department':
['Sales' 'Research & Development' 'Human Resources']


Unique values for column 'DistanceFromHome':
[ 1  8  2  3 24 23 27 16 15 26 19 21  5 11  9  7  6 10  4 25 12 18 29 22
 14 20 28 17 13]


Unique values for column 'Education':
[2 1 4 3 5]


Unique values for column 'EducationField':
['Life Sciences' 'Other' 'Medical' 'Marketing' 'Technical Degree'
 'Human Resources']


Unique values for column 'EmployeeCount':
[1]


Unique values for column 'EmployeeNumber':
[   1    2    4 ... 2064 2065 2068]


Unique values for column 'EnvironmentSatisfaction':
[2 3 4 1]


Unique values for column 'Gender':
['Female' 'Male']


Unique values for column 'HourlyRate':
[ 94  61  92  56  40  79  81  67  44  84  49  31  93  50  51  80  96  78
  45  82  53  83  58  72  48  42  41  86  97  75  33  37  73  98  36  47
  71  30  43  99  59  95  57  76  87  66  55  32  52  70  62  64  63  60
 100  46  39  77  35  91  54  34  90  65  88  85  89  68  69  74  38]


Unique values for column 'JobInvolvement':
[3 2 4 1]


Unique values for column 'JobLevel':
[2 1 3 4 5]


Unique values for column 'JobRole':
['Sales Executive' 'Research Scientist' 'Laboratory Technician'
 'Manufacturing Director' 'Healthcare Representative' 'Manager'
 'Sales Representative' 'Research Director' 'Human Resources']


Unique values for column 'JobSatisfaction':
[4 2 3 1]


Unique values for column 'MaritalStatus':
['Single' 'Married' 'Divorced']


Unique values for column 'MonthlyIncome':
[5993 5130 2090 ... 9991 5390 4404]


Unique values for column 'MonthlyRate':
[19479 24907  2396 ...  5174 13243 10228]


Unique values for column 'NumCompaniesWorked':
[8 1 6 9 0 4 5 2 7 3]


Unique values for column 'Over18':
['Y']


Unique values for column 'OverTime':
['Yes' 'No']


Unique values for column 'PercentSalaryHike':
[11 23 15 12 13 20 22 21 17 14 16 18 19 24 25]


Unique values for column 'PerformanceRating':
[3 4]


Unique values for column 'RelationshipSatisfaction':
[1 4 2 3]


Unique values for column 'StandardHours':
[80]


Unique values for column 'StockOptionLevel':
[0 1 3 2]


Unique values for column 'TotalWorkingYears':
[ 8 10  7  6 12  1 17  5  3 31 13  0 26 24 22  9 19  2 23 14 15  4 29 28
 21 25 20 11 16 37 38 30 40 18 36 34 32 33 35 27]


Unique values for column 'TrainingTimesLastYear':
[0 3 2 5 1 4 6]


Unique values for column 'WorkLifeBalance':
[1 3 2 4]


Unique values for column 'YearsAtCompany':
[ 6 10  0  8  2  7  1  9  5  4 25  3 12 14 22 15 27 21 17 11 13 37 16 20
 40 24 33 19 36 18 29 31 32 34 26 30 23]


Unique values for column 'YearsInCurrentRole':
[ 4  7  0  2  5  9  8  3  6 13  1 15 14 16 11 10 12 18 17]


Unique values for column 'YearsSinceLastPromotion':
[ 0  1  3  2  7  4  8  6  5 15  9 13 12 10 11 14]


Unique values for column 'YearsWithCurrManager':
[ 5  7  0  2  6  8  3 11 17  1  4 12  9 10 15 13 16 14]

# Data Cleaning

1. Encoding
2. Dropping unnecessary colums

In [8]:
# Binary categorical mappings
attrition_mapping = {'No': 0, 'Yes': 1}
gender_mapping = {'Male': 0, 'Female': 1}
overtime_mapping = {'No': 0, 'Yes': 1}

# Nominal categorical mappings
business_travel_mapping = {
    'Non-Travel': 0,
    'Travel_Rarely': 1,
    'Travel_Frequently': 2
}

department_mapping = {
    'Sales': 0,
    'Research & Development': 1,
    'Human Resources': 2
}

education_field_mapping = {
    'Life Sciences': 0,
    'Medical': 1,
    'Marketing': 2,
    'Technical Degree': 3,
    'Human Resources': 4,
    'Other': 5
}

job_role_mapping = {
    'Sales Executive': 0,
    'Research Scientist': 1,
    'Laboratory Technician': 2,
    'Manufacturing Director': 3,
    'Healthcare Representative': 4,
    'Manager': 5,
    'Sales Representative': 6,
    'Research Director': 7,
    'Human Resources': 8
}

marital_status_mapping = {
    'Single': 0,
    'Married': 1,
    'Divorced': 2
}

# Apply mappings
df['Attrition'] = df['Attrition'].map(attrition_mapping)
df['Gender'] = df['Gender'].map(gender_mapping)
df['OverTime'] = df['OverTime'].map(overtime_mapping)

df['BusinessTravel'] = df['BusinessTravel'].map(business_travel_mapping)
df['Department'] = df['Department'].map(department_mapping)
df['EducationField'] = df['EducationField'].map(education_field_mapping)
df['JobRole'] = df['JobRole'].map(job_role_mapping)
df['MaritalStatus'] = df['MaritalStatus'].map(marital_status_mapping)

encoded_cols = [
    'Attrition',
    'Gender',
    'OverTime',
    'BusinessTravel',
    'Department',
    'EducationField',
    'JobRole',
    'MaritalStatus'
]

for col in encoded_cols:
    print(f"Unique values for column '{col}':")
    print(df[col].unique())
    print("\n")

Unique values for column 'Attrition':
[1 0]


Unique values for column 'Gender':
[1 0]


Unique values for column 'OverTime':
[1 0]


Unique values for column 'BusinessTravel':
[1 2 0]


Unique values for column 'Department':
[0 1 2]


Unique values for column 'EducationField':
[0 5 1 2 3 4]


Unique values for column 'JobRole':
[0 1 2 3 4 5 6 7 8]


Unique values for column 'MaritalStatus':
[0 1 2]

In [9]:
# Drop unnecessary columns
df.drop(['EmployeeCount',
         'Over18',
         'StandardHours',
         'EmployeeNumber'], axis=1, inplace=True)

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 31 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1470 non-null   int64
 1   Attrition                 1470 non-null   int64
 2   BusinessTravel            1470 non-null   int64
 3   DailyRate                 1470 non-null   int64
 4   Department                1470 non-null   int64
 5   DistanceFromHome          1470 non-null   int64
 6   Education                 1470 non-null   int64
 7   EducationField            1470 non-null   int64
 8   EnvironmentSatisfaction   1470 non-null   int64
 9   Gender                    1470 non-null   int64
 10  HourlyRate                1470 non-null   int64
 11  JobInvolvement            1470 non-null   int64
 12  JobLevel                  1470 non-null   int64
 13  JobRole                   1470 non-null   int64
 14  JobSatisfaction           1470 non-null   int64
 15  MaritalStatus             1470 non-null   int64
 16  MonthlyIncome             1470 non-null   int64
 17  MonthlyRate               1470 non-null   int64
 18  NumCompaniesWorked        1470 non-null   int64
 19  OverTime                  1470 non-null   int64
 20  PercentSalaryHike         1470 non-null   int64
 21  PerformanceRating         1470 non-null   int64
 22  RelationshipSatisfaction  1470 non-null   int64
 23  StockOptionLevel          1470 non-null   int64
 24  TotalWorkingYears         1470 non-null   int64
 25  TrainingTimesLastYear     1470 non-null   int64
 26  WorkLifeBalance           1470 non-null   int64
 27  YearsAtCompany            1470 non-null   int64
 28  YearsInCurrentRole        1470 non-null   int64
 29  YearsSinceLastPromotion   1470 non-null   int64
 30  YearsWithCurrManager      1470 non-null   int64
dtypes: int64(31)
memory usage: 356.1 KB

# Data Balancing

In [12]:
X = df.drop('Attrition', axis=1)
y = df['Attrition']

In [13]:
smote = SMOTE(random_state=42)
X_resampled, y_resampled = smote.fit_resample(X, y)
print("Class distribution after SMOTE:", pd.Series(y_resampled).value_counts())

Class distribution after SMOTE: Attrition
1    1233
0    1233
Name: count, dtype: int64

# Train-Test split

In [14]:
X_train, X_test, y_train, y_test = train_test_split(
    X_resampled, y_resampled, test_size=0.2, random_state=46, stratify=y_resampled
)

In [17]:
print("Shape of X_train:", X_train.shape)
print("Shape of X_test:", X_test.shape)
print("Shape of y_train:", y_train.shape)
print("Shape of y_test:", y_test.shape)

Shape of X_train: (1972, 30)
Shape of X_test: (494, 30)
Shape of y_train: (1972,)
Shape of y_test: (494,)

# Model Building

In [15]:
models = {
    "LogisticRegression": LogisticRegression(),
    "SVC": SVC(),
    "LinearSVC": LinearSVC(),
    "KNeighborsClassifier": KNeighborsClassifier(),
    "DecisionTreeClassifier": DecisionTreeClassifier(),
    "ExtraTreeClassifier": ExtraTreeClassifier(),
    "RandomForestClassifier": RandomForestClassifier(),
    "GradientBoostingClassifier": GradientBoostingClassifier(),
    "AdaBoostClassifier": AdaBoostClassifier(),
    "ExtraTreesClassifier": ExtraTreesClassifier(),
    "GaussianNB": GaussianNB(),
    "BernoulliNB": BernoulliNB(),
    "LinearDiscriminantAnalysis": LinearDiscriminantAnalysis(),
    "QuadraticDiscriminantAnalysis": QuadraticDiscriminantAnalysis()
}

# Evaluation

In [16]:
model_results = train_and_evaluate_models(models, X_train, X_test, y_train, y_test)

Training LogisticRegression...
LogisticRegression metrics:
  Accuracy: 0.7024
  Precision: 0.7033
  F1 Score: 0.7018
  Recall: 0.7004
  AUC: 0.7024
Training SVC...

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

SVC metrics:
  Accuracy: 0.6053
  Precision: 0.5839
  F1 Score: 0.6499
  Recall: 0.7328
  AUC: 0.6053
Training LinearSVC...
LinearSVC metrics:
  Accuracy: 0.8320
  Precision: 0.8306
  F1 Score: 0.8323
  Recall: 0.8340
  AUC: 0.8320
Training KNeighborsClassifier...
KNeighborsClassifier metrics:
  Accuracy: 0.7591
  Precision: 0.7065
  F1 Score: 0.7864
  Recall: 0.8866
  AUC: 0.7591
Training DecisionTreeClassifier...
DecisionTreeClassifier metrics:
  Accuracy: 0.8057
  Precision: 0.7807
  F1 Score: 0.8140
  Recall: 0.8502
  AUC: 0.8057
Training ExtraTreeClassifier...
ExtraTreeClassifier metrics:
  Accuracy: 0.8279
  Precision: 0.8022
  F1 Score: 0.8350
  Recall: 0.8704
  AUC: 0.8279
Training RandomForestClassifier...
RandomForestClassifier metrics:
  Accuracy: 0.9271
  Precision: 0.9271
  F1 Score: 0.9271
  Recall: 0.9271
  AUC: 0.9271
Training GradientBoostingClassifier...
GradientBoostingClassifier metrics:
  Accuracy: 0.9109
  Precision: 0.9076
  F1 Score: 0.9113
  Recall: 0.9150
  AUC: 0.9109
Training AdaBoostClassifier...
AdaBoostClassifier metrics:
  Accuracy: 0.8765
  Precision: 0.8605
  F1 Score: 0.8792
  Recall: 0.8988
  AUC: 0.8765
Training ExtraTreesClassifier...
ExtraTreesClassifier metrics:
  Accuracy: 0.9332
  Precision: 0.9350
  F1 Score: 0.9331
  Recall: 0.9312
  AUC: 0.9332
Training GaussianNB...
GaussianNB metrics:
  Accuracy: 0.7753
  Precision: 0.7378
  F1 Score: 0.7917
  Recall: 0.8543
  AUC: 0.7753
Training BernoulliNB...
BernoulliNB metrics:
  Accuracy: 0.7206
  Precision: 0.7359
  F1 Score: 0.7113
  Recall: 0.6883
  AUC: 0.7206
Training LinearDiscriminantAnalysis...
LinearDiscriminantAnalysis metrics:
  Accuracy: 0.8563
  Precision: 0.8411
  F1 Score: 0.8594
  Recall: 0.8785
  AUC: 0.8563
Training QuadraticDiscriminantAnalysis...
QuadraticDiscriminantAnalysis metrics:
  Accuracy: 0.8583
  Precision: 0.8365
  F1 Score: 0.8627
  Recall: 0.8907
  AUC: 0.8583